name: PHP turd

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                                 libselinux-dev php-cli bats
      - name: Autotools
        run: |
          ./autogen.sh
      - name: Configure
        run: |
          ./configure
      - name: Build
        run: |
          make
      - name: Test
        run: |
          make check
      - name: Upload test artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tests
          path: .
      - name: Distribution
        run: |
          make distcheck
      - name: Check for release version
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          echo "::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\/v/}"
      - name: Create release
        id: create_release
        if: env.RELEASE_VERSION
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: Upload release assets
        if: env.RELEASE_VERSION
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: phpturd-${{ env.RELEASE_VERSION }}.tar.gz
          asset_name: phpturd-${{ env.RELEASE_VERSION }}.tar.gz
          asset_content_type: application/x-gtar
